UF_CHOICES = (
    (u'0', '-- Selecione --'),
    (u'1', 'AC'),
    (u'2', 'AL'),
    (u'3', 'AM'),
    (u'4', 'AP'),
    (u'5', 'BA'),
    (u'6', 'CE'),
    (u'7', 'DF'),
    (u'8', 'ES'),
    (u'9', 'GO'),
    (u'10', 'MA'),
    (u'11', 'MG'),
    (u'12', 'MS'),
    (u'13', 'MT'),
    (u'14', 'PA'),
    (u'15', 'PB'),
    (u'16', 'PE'),
    (u'17', 'PI'),
    (u'18', 'PR'),
    (u'19', 'RJ'),
    (u'20', 'RN'),
    (u'21', 'RO'),
    (u'22', 'RR'),
    (u'23', 'RS'),
    (u'24', 'SC'),
    (u'25', 'SE'),
    (u'26', 'SP'),
    (u'27', 'TO'),
)

LOGRADOURO_CHOICES = (
    (u'0', '-- Selecione --'),
    (u'1', 'Area'),
    (u'2', 'Acesso'),
    (u'3', 'Acesso Local'),
    (u'4', 'Alameda'),
    (u'5', 'Avenida'),
    (u'6', 'Conjunto'),
    (u'7', 'Condomínio'),
    (u'8', 'Distrito'),
    (u'9', 'Estrada'),
    (u'10', 'Lote'),
    (u'11', 'Quadra'),
    (u'12', 'Setor'),
    (u'13', 'Rua'),
    (u'14', 'Via'),
    (u'15', 'Via de Acesso'),
)