# Generated by Django 3.0.4 on 2020-03-16 14:43

import cloudinary.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('nome', models.CharField(max_length=20, verbose_name='Nome Funcionario')),
                ('sobrenome', models.CharField(max_length=100, verbose_name='Sobrenome')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='Email')),
                ('cpf', models.CharField(blank=True, max_length=14, null=True, verbose_name='CPF')),
                ('celular', models.CharField(max_length=11, null=True, verbose_name='Numero de Telefone')),
                ('nivel_funcionario', models.CharField(blank=True, max_length=10, verbose_name='Nível Funcionario')),
                ('coordenador', models.CharField(blank=True, max_length=20)),
                ('selfie_usuario', cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='self_usuario')),
                ('data_nasc', models.CharField(max_length=12)),
                ('cep', models.CharField(blank=True, max_length=9, null=True)),
                ('logradouro', models.CharField(blank=True, max_length=75, null=True)),
                ('numero', models.CharField(blank=True, max_length=6, null=True)),
                ('bairro', models.CharField(blank=True, max_length=100, null=True)),
                ('complemento', models.CharField(blank=True, max_length=100, null=True)),
                ('municipio', models.CharField(blank=True, max_length=50, null=True)),
                ('estado', models.CharField(choices=[('0', '-- Selecione --'), ('1', 'AC'), ('2', 'AL'), ('3', 'AM'), ('4', 'AP'), ('5', 'BA'), ('6', 'CE'), ('7', 'DF'), ('8', 'ES'), ('9', 'GO'), ('10', 'MA'), ('11', 'MG'), ('12', 'MS'), ('13', 'MT'), ('14', 'PA'), ('15', 'PB'), ('16', 'PE'), ('17', 'PI'), ('18', 'PR'), ('19', 'RJ'), ('20', 'RN'), ('21', 'RO'), ('22', 'RR'), ('23', 'RS'), ('24', 'SC'), ('25', 'SE'), ('26', 'SP'), ('27', 'TO')], default='0', max_length=2)),
                ('reset_pass', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'MyUser',
            },
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_empresa', models.CharField(max_length=20, null=True, unique=True, verbose_name='Nome da Empresa')),
                ('telefone_empresa', models.CharField(max_length=15, null=True, verbose_name='Contato da Empresa')),
                ('email', models.EmailField(max_length=255, null=True, verbose_name='Email')),
                ('logomarca', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='logomarca')),
                ('razao_social', models.CharField(max_length=100, null=True)),
                ('nome_fantasia', models.CharField(max_length=50, null=True)),
                ('cnpj', models.CharField(max_length=20, null=True, verbose_name='CNPJ')),
                ('insc_estad', models.CharField(blank=True, max_length=20, null=True, verbose_name='IE')),
                ('tipo_logradouro', models.CharField(choices=[('0', '-- Selecione --'), ('1', 'Area'), ('2', 'Acesso'), ('3', 'Acesso Local'), ('4', 'Alameda'), ('5', 'Avenida'), ('6', 'Conjunto'), ('7', 'Condomínio'), ('8', 'Distrito'), ('9', 'Estrada'), ('10', 'Lote'), ('11', 'Quadra'), ('12', 'Setor'), ('13', 'Rua'), ('14', 'Via'), ('15', 'Via de Acesso')], default='0', max_length=3)),
                ('logradouro', models.CharField(max_length=75, null=True)),
                ('numero', models.CharField(max_length=6, null=True)),
                ('bairro', models.CharField(max_length=100, null=True)),
                ('complemento', models.CharField(max_length=100, null=True)),
                ('municipio', models.CharField(max_length=50, null=True)),
                ('estado', models.CharField(blank=True, choices=[('0', '-- Selecione --'), ('1', 'AC'), ('2', 'AL'), ('3', 'AM'), ('4', 'AP'), ('5', 'BA'), ('6', 'CE'), ('7', 'DF'), ('8', 'ES'), ('9', 'GO'), ('10', 'MA'), ('11', 'MG'), ('12', 'MS'), ('13', 'MT'), ('14', 'PA'), ('15', 'PB'), ('16', 'PE'), ('17', 'PI'), ('18', 'PR'), ('19', 'RJ'), ('20', 'RN'), ('21', 'RO'), ('22', 'RR'), ('23', 'RS'), ('24', 'SC'), ('25', 'SE'), ('26', 'SP'), ('27', 'TO')], default='0', max_length=2, null=True)),
                ('data_registro', models.DateField(auto_now_add=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'Cliente',
            },
        ),
        migrations.CreateModel(
            name='Equipes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_equipe', models.CharField(blank=True, max_length=200, null=True)),
                ('coordenador', models.CharField(blank=True, max_length=255, null=True)),
                ('qtdIntegrante', models.IntegerField(blank=True, default=0, null=True)),
                ('integrantes', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'Equipe',
            },
        ),
        migrations.CreateModel(
            name='Feriado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feriado', models.CharField(blank=True, max_length=200, null=True)),
                ('dia_mes_ano', models.DateTimeField(default=datetime.datetime.now)),
                ('cidade', models.CharField(blank=True, max_length=50, null=True, verbose_name='cidade')),
                ('local', models.CharField(blank=True, max_length=50, null=True, verbose_name='local')),
            ],
            options={
                'db_table': 'Feriado',
            },
        ),
        migrations.CreateModel(
            name='ParametrosOS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(blank=True, max_length=30, null=True)),
                ('data_inicial', models.CharField(max_length=10)),
                ('data_final', models.CharField(max_length=10)),
                ('nivel_func', models.CharField(max_length=10, null=True, verbose_name='Nível Funcionario')),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'Parametros',
            },
        ),
        migrations.CreateModel(
            name='Projetos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_projeto', models.CharField(max_length=20, null=True, verbose_name='nome projeto')),
                ('solicitante', models.CharField(max_length=20, null=True, verbose_name='Solicitante')),
                ('anexo_projeto', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='anexo_projeto')),
                ('data_horario_inicio', models.CharField(max_length=12)),
                ('data_horario_conclusao', models.CharField(max_length=12)),
                ('observacao', models.CharField(max_length=20, null=True, verbose_name='observação')),
                ('ativo', models.BooleanField(default=True)),
                ('clientes', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Clientes')),
                ('equipes', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='core.Equipes')),
                ('myuser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Projetos',
            },
        ),
        migrations.CreateModel(
            name='CadastroOS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anexo_cliente', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='anexo_cliente')),
                ('solicitante', models.CharField(blank=True, max_length=20, null=True, verbose_name='Solicitante')),
                ('traslado', models.TimeField(auto_now_add=True, verbose_name='Conversation Time')),
                ('desconto', models.FloatField(default=0, null=True)),
                ('h50', models.TimeField(blank=True, verbose_name='Conversation Time')),
                ('h100', models.TimeField(blank=True, verbose_name='Conversation Time')),
                ('total', models.TimeField(blank=True, verbose_name='Conversation Time')),
                ('valor', models.FloatField(blank=True, default=0, null=True)),
                ('horas_hoje', models.TimeField(blank=True, verbose_name='Conversation Time')),
                ('data_horario_inicio', models.CharField(max_length=12)),
                ('data_horario_conclusao', models.CharField(max_length=12)),
                ('observacao', models.CharField(blank=True, max_length=20, null=True, verbose_name='observação')),
                ('anexo', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='anexo')),
                ('status', models.BooleanField(default=True)),
                ('clientes', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Clientes')),
                ('equipes', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Equipes')),
                ('myuser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('projetos', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Projetos')),
            ],
            options={
                'db_table': 'CadastroOS',
            },
        ),
    ]
